version: "3.9"
services:
  database:
    image: mysql-database:latest
    build: 
      context: ./MySQL
      dockerfile: Dockerfile
      network: "host"
    ports:
      - "3306:3306"
    volumes:
      - ./MySQL/data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - database
    
    
  backend:
    image: rip-backend:latest
    build: 
      context: ./backend
      dockerfile: Dockerfile
      network: "host"
    volumes:
      - ./backend/staticfiles:/backend/staticfiles
      - ./backend/media:/backend/media
    ports:
      - "8000:8000"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/staticfiles:/staticfiles
      - ./backend/media:/media
    depends_on:
      - backend

      