# Generated by Django 5.1.1 on 2024-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animalad_breed_alter_animalad_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalad',
            name='breed',
            field=models.CharField(max_length=100, verbose_name='Порода животного'),
        ),
        migrations.AlterField(
            model_name='animalad',
            name='kind',
            field=models.CharField(choices=[('Dog', 'Собака'), ('Cat', 'Кот')], max_length=100, verbose_name='Вид животного'),
        ),
    ]
