# Generated by Django 5.1.1 on 2024-10-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_message_room_message_room_id_delete_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=50, verbose_name='Имя чата')),
                ('support_read', models.BooleanField(default=False, max_length=50, verbose_name='Прочитан техподдержкой')),
            ],
        ),
    ]
