version: "3.9"
services:
  database:
    image: mysql-database:latest
    build: .
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
