# Generated by Django 5.1.1 on 2024-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='support_read',
            field=models.BooleanField(default=True, max_length=50, verbose_name='Прочитан техподдержкой'),
        ),
    ]
